#!/bin/bash 

#tsFiles=$(find . -type f -name *.ts | grep -v [.]d[.]ts | grep -v /test/ | grep -v target)

# install yuidoc using the steps mentioned here -> http://yui.github.io/yuidoc/##install
# or tl;dr just do npm install -g yuidocjs

src=src/main/webapp/app
out=target/docs
theme=../hawtio-docs/theme


# Generate docs
function gen {
  yuidoc -e .ts -t $theme -o $out $src
}

# starts yuidoc in server mode
function server {
  yuidoc -e .ts -t $theme -o $out --server $src
}

# Just evaluates JSDoc comments
function lint {
  yuidoc -e .ts -t $theme -o $out --lint $src
}

action='lint'

case $1 in
  -s|--server)
  action='server'
  ;;
  -g|--generate)
  action='gen'
  ;;
esac

echo "doing action $action"
$action


