declare var io_hawt_dozer_schema_Field: any;
declare var io_hawt_dozer_schema_FieldExclude: any;
declare var io_hawt_dozer_schema_Mapping: any;
declare var io_hawt_dozer_schema_Mappings: any;

declare var org_fusesource_fabric_api_CreateChildContainerOptions: any;
declare var org_fusesource_fabric_service_jclouds_CreateJCloudsContainerOptions: any;
declare var org_fusesource_fabric_service_ssh_CreateSshContainerOptions: any;
