cacheFolder: ../.yarn/cache

compressionLevel: mixed

defaultSemverRangePrefix: ^

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  '@module-federation/utilities@*':
    peerDependenciesMeta:
      webpack:
        optional: true
  '@patternfly/react-code-editor@*':
    peerDependencies:
      monaco-editor: ^0.52.0

yarnPath: ../.yarn/releases/yarn-4.10.3.cjs
